package deploy

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

const generatedMarker = "# Generated by Ray; configure commands in project setup.\n"

func shellInstruction(kind, command string) string {
	encoded, _ := json.Marshal([]string{"/bin/sh", "-c", command})
	return kind + " " + string(encoded) + "\n"
}
func DetectAndGenerateDockerfile(root string, options ...DeployRequest) (string, int, error) {
	var req DeployRequest
	if len(options) > 0 {
		req = options[0]
	}
	for _, command := range []string{req.BuildCommand, req.StartCommand} {
		if len(command) > 4096 || strings.ContainsAny(command, "\x00\r\n") {
			return "", 0, fmt.Errorf("commands must be single lines up to 4096 bytes")
		}
	}
	filename := filepath.Join(root, "Dockerfile")
	if info, err := os.Lstat(filename); err == nil && !info.Mode().IsRegular() {
		return "", 0, fmt.Errorf("Dockerfile must be a regular file")
	}
	if data, err := os.ReadFile(filename); err == nil && len(data) > 0 && !strings.HasPrefix(string(data), generatedMarker) {
		if req.BuildCommand != "" {
			return "", 0, fmt.Errorf("set the build command inside your custom Dockerfile")
		}
		port := 3000
		for _, line := range strings.Split(string(data), "\n") {
			parts := strings.Fields(line)
			if len(parts) > 1 && strings.EqualFold(parts[0], "EXPOSE") {
				p, _ := strconv.Atoi(strings.TrimSuffix(parts[1], "/tcp"))
				if p > 0 && p <= 65535 {
					port = p
				}
			}
		}
		return string(data), port, nil
	}
	content, port, err := generateTemplate(root, req)
	if err != nil {
		return "", 0, err
	}
	content = generatedMarker + content
	if err = os.WriteFile(filename, []byte(content), 0644); err != nil {
		return "", 0, err
	}
	ignore := filepath.Join(root, ".dockerignore")
	if !fileExists(ignore) {
		if err = os.WriteFile(ignore, []byte(".git\nnode_modules\n.next\n.nuxt\n.output\n.venv\n__pycache__\ntarget\n.env\n.env.*\n!.env.example\n"), 0644); err != nil {
			return "", 0, err
		}
	}
	return content, port, nil
}
func generateTemplate(root string, req DeployRequest) (string, int, error) {
	var pkg struct {
		Dependencies    map[string]string `json:"dependencies"`
		DevDependencies map[string]string `json:"devDependencies"`
		Scripts         map[string]string `json:"scripts"`
		PackageManager  string            `json:"packageManager"`
	}
	data, _ := os.ReadFile(filepath.Join(root, "package.json"))
	if len(data) > 0 {
		if err := json.Unmarshal(data, &pkg); err != nil {
			return "", 0, fmt.Errorf("invalid package.json")
		}
	}
	has := func(name string) bool { return pkg.Dependencies[name] != "" || pkg.DevDependencies[name] != "" }
	framework := req.Framework
	if framework == "" || framework == "auto" {
		switch {
		case has("next"):
			framework = "nextjs"
		case has("nuxt"):
			framework = "nuxt"
		case has("@sveltejs/kit"):
			framework = "sveltekit"
		case has("vite") || has("react-scripts") || has("react") || has("vue"):
			framework = "react"
		case len(data) > 0:
			framework = "node"
		case fileExists(filepath.Join(root, "manage.py")):
			framework = "django"
		case fileExists(filepath.Join(root, "go.mod")):
			framework = "go"
		case fileExists(filepath.Join(root, "Cargo.toml")):
			framework = "rust"
		case fileExists(filepath.Join(root, "artisan")):
			framework = "laravel"
		case fileExists(filepath.Join(root, "composer.json")) || fileExists(filepath.Join(root, "index.php")):
			framework = "php"
		case fileExists(filepath.Join(root, "Gemfile")):
			framework = "ruby"
		case fileExists(filepath.Join(root, "pom.xml")) || fileExists(filepath.Join(root, "build.gradle")) || fileExists(filepath.Join(root, "build.gradle.kts")):
			framework = "java"
		case fileExists(filepath.Join(root, "requirements.txt")) || fileExists(filepath.Join(root, "pyproject.toml")):
			framework = "python"
			for _, manifest := range []string{"requirements.txt", "pyproject.toml"} {
				raw, _ := os.ReadFile(filepath.Join(root, manifest))
				lower := strings.ToLower(string(raw))
				if strings.Contains(lower, "django") {
					framework = "django"
					break
				}
				if strings.Contains(lower, "fastapi") {
					framework = "fastapi"
					break
				}
				if strings.Contains(lower, "flask") {
					framework = "flask"
					break
				}
			}
		case fileExists(filepath.Join(root, "index.html")):
			framework = "static"
		default:
			return "", 0, fmt.Errorf("cannot select a production template; choose a framework or provide a Dockerfile")
		}
	}
	port := 3000
	image := ""
	install := ""
	build := req.BuildCommand
	start := req.StartCommand
	prefix := ""
	suffix := ""
	user := "10001:10001"
	switch framework {
	case "nextjs", "nuxt", "sveltekit", "node", "express", "fastify", "react", "vue":
		if len(data) == 0 {
			return "", 0, fmt.Errorf("%s requires package.json", framework)
		}
		image = "node:22-bookworm-slim"
		manager := "npm"
		install = "npm install --include=dev"
		if fileExists(filepath.Join(root, "package-lock.json")) {
			install = "npm ci --include=dev"
		}
		if fileExists(filepath.Join(root, "pnpm-lock.yaml")) {
			manager = "pnpm"
			if !strings.HasPrefix(pkg.PackageManager, "pnpm@") {
				return "", 0, fmt.Errorf("pin pnpm in package.json packageManager")
			}
			install = "corepack enable && pnpm install --frozen-lockfile"
		}
		if fileExists(filepath.Join(root, "yarn.lock")) {
			manager = "yarn"
			if !strings.HasPrefix(pkg.PackageManager, "yarn@") {
				return "", 0, fmt.Errorf("pin Yarn in package.json packageManager")
			}
			install = "corepack enable && yarn install --immutable"
			if strings.HasPrefix(pkg.PackageManager, "yarn@1.") {
				install = "corepack enable && yarn install --frozen-lockfile"
			}
		}
		if build == "" && pkg.Scripts["build"] != "" {
			build = manager + " run build"
		}
		if start == "" {
			switch framework {
			case "nextjs":
				start = "node node_modules/next/dist/bin/next start -H 0.0.0.0 -p \"$PORT\""
			case "nuxt":
				start = "node .output/server/index.mjs"
			case "sveltekit":
				if !has("@sveltejs/adapter-node") {
					return "", 0, fmt.Errorf("SvelteKit requires configured @sveltejs/adapter-node or a custom Dockerfile")
				}
				start = "node build"
			default:
				if pkg.Scripts["start"] != "" {
					start = manager + " start"
				}
			}
		}
		if framework == "react" || framework == "vue" {
			if build == "" {
				return "", 0, fmt.Errorf("static frontend requires a build script or build command")
			}
			output := "dist"
			if has("react-scripts") {
				output = "build"
			}
			if req.StartCommand != "" {
				return "", 0, fmt.Errorf("static frontend templates use nginx; use a custom Dockerfile for a different server")
			}
			port = 8080
			if req.ContainerPort > 0 {
				port = req.ContainerPort
			}
			return "FROM " + image + " AS builder\nWORKDIR /app\nCOPY . .\n" + shellInstruction("RUN", install) + shellInstruction("RUN", build) + staticRuntime("COPY --from=builder /app/"+output+" /usr/share/nginx/html\n", port, true), port, nil
		}
	case "django", "fastapi", "flask", "python":
		image = "python:3.12-slim"
		port = 8000
		switch {
		case fileExists(filepath.Join(root, "requirements.txt")):
			install = "pip install --no-cache-dir -r requirements.txt"
		case fileExists(filepath.Join(root, "pyproject.toml")) || fileExists(filepath.Join(root, "setup.py")):
			install = "pip install --no-cache-dir ."
		default:
			return "", 0, fmt.Errorf("Python template needs requirements.txt or an installable pyproject.toml")
		}
		if start == "" {
			switch framework {
			case "django":
				matches, _ := filepath.Glob(filepath.Join(root, "*", "wsgi.py"))
				if len(matches) == 1 {
					module := filepath.Base(filepath.Dir(matches[0]))
					if regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`).MatchString(module) {
						start = "gunicorn " + module + ".wsgi:application --bind 0.0.0.0:$PORT"
					}
				}
			case "fastapi":
				start = "uvicorn main:app --host 0.0.0.0 --port $PORT"
			case "flask":
				start = "gunicorn app:app --bind 0.0.0.0:$PORT"
			}
		}
	case "go":
		port = 8080
		if build == "" {
			build = "CGO_ENABLED=0 go build -o /out/server ."
		}
		if start == "" {
			start = "./server"
		}
		prefix = "FROM golang:1.26-bookworm AS builder\nWORKDIR /src\nCOPY . .\n" + shellInstruction("RUN", "go mod download") + shellInstruction("RUN", build)
		image = "debian:bookworm-slim"
		install = "apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*"
		suffix = "COPY --from=builder /out/server /app/server\n"
		build = ""
	case "rust":
		port = 8080
		image = "rust:1-bookworm"
		install = ""
		if build == "" {
			build = "cargo build --release --locked"
		}
		// Multiple binaries and workspace packages need an explicit entry point.
		if start == "" {
			return "", 0, fmt.Errorf("Rust requires a start command, e.g. ./target/release/my-server")
		}
	case "java":
		port = 8080
		image = "eclipse-temurin:21-jdk-jammy"
		if build == "" {
			switch {
			case fileExists(filepath.Join(root, "mvnw")):
				build = "sh ./mvnw -B package -DskipTests"
			case fileExists(filepath.Join(root, "gradlew")):
				build = "sh ./gradlew build -x test --no-daemon"
			default:
				return "", 0, fmt.Errorf("Java requires a Maven/Gradle wrapper or a custom Dockerfile")
			}
		}
		if start == "" {
			return "", 0, fmt.Errorf("Java requires the exact jar start command, e.g. java -jar target/app.jar")
		}
	case "ruby":
		image = "ruby:3.3-slim-bookworm"
		install = "bundle install"
		if start == "" && fileExists(filepath.Join(root, "bin", "rails")) {
			start = "bundle exec rails server -b 0.0.0.0 -p $PORT"
		}
	case "php", "laravel":
		port = 80
		image = "php:8.3-apache-bookworm"
		user = ""
		prefix = "FROM composer:2 AS composer\n"
		suffix = "COPY --from=composer /usr/bin/composer /usr/local/bin/composer\n"
		if fileExists(filepath.Join(root, "composer.json")) {
			install = "composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader"
		}
		suffix += "RUN a2enmod rewrite\n"
		docroot := "/app"
		if framework == "laravel" {
			docroot = "/app/public"
			suffix += "RUN docker-php-ext-install pdo_mysql\n"
		}
		suffix += shellInstruction("RUN", "sed -ri 's!/var/www/html!"+docroot+"!g' /etc/apache2/sites-available/*.conf && printf '<Directory "+docroot+">\\nAllowOverride All\\nRequire all granted\\n</Directory>\\n' > /etc/apache2/conf-enabled/ray.conf")
		if framework == "laravel" {
			suffix += "RUN mkdir -p storage bootstrap/cache && chown -R www-data:www-data storage bootstrap/cache\n"
		}
		if start == "" {
			start = "apache2-foreground"
		}
	case "static":
		if build != "" || start != "" {
			return "", 0, fmt.Errorf("static template needs no build/start override; provide a custom Dockerfile for preprocessing")
		}
		port = 8080
		if req.ContainerPort > 0 {
			port = req.ContainerPort
		}
		return staticRuntime("COPY . /usr/share/nginx/html\n", port, false), port, nil
	default:
		return "", 0, fmt.Errorf("framework %s requires a custom Dockerfile", framework)
	}
	if req.ContainerPort > 0 {
		port = req.ContainerPort
	}
	if (framework == "php" || framework == "laravel") && port != 80 {
		suffix += shellInstruction("RUN", "sed -ri 's/Listen 80/Listen "+strconv.Itoa(port)+"/' /etc/apache2/ports.conf && sed -ri 's/[*]:80/*:"+strconv.Itoa(port)+"/g' /etc/apache2/sites-available/*.conf")
	}
	if start == "" {
		return "", 0, fmt.Errorf("%s needs an explicit production start command", framework)
	}
	content := prefix + "FROM " + image + "\nWORKDIR /app\n"
	if framework != "go" {
		content += "COPY . .\n"
	}
	content += suffix
	if install != "" {
		content += shellInstruction("RUN", install)
	}
	if build != "" {
		content += shellInstruction("RUN", build)
	}
	content += "ENV NODE_ENV=production PYTHONUNBUFFERED=1 RAILS_ENV=production HOST=0.0.0.0 PORT=" + strconv.Itoa(port) + "\n"
	if user != "" {
		content += "RUN mkdir -p /home/ray && chown -R 10001:10001 /app /home/ray\nENV HOME=/home/ray\nUSER " + user + "\n"
	}
	content += "EXPOSE " + strconv.Itoa(port) + "\n" + shellInstruction("CMD", start)
	return content, port, nil
}

func staticRuntime(copyLine string, port int, spa bool) string {
	fallback := "=404"
	if spa {
		fallback = "/index.html"
	}
	command := "printf '%s\\n' 'server {' 'listen " + strconv.Itoa(port) + ";' 'listen [::]:" + strconv.Itoa(port) + ";' 'root /usr/share/nginx/html;' 'index index.html;' 'location / { try_files $uri $uri/ " + fallback + "; }' '}' > /etc/nginx/conf.d/default.conf"
	return "FROM nginxinc/nginx-unprivileged:stable-alpine\nUSER root\n" + shellInstruction("RUN", command) + copyLine + "USER 101\nEXPOSE " + strconv.Itoa(port) + "\n"
}
